<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class NigerianCitiesSeeder extends Seeder
{
    public function run(): void
    {
        $map = 
array (
  'Abia' => 
  array (
    0 => 'Aba North',
    1 => 'Aba South',
    2 => 'Arochukwu',
    3 => 'Bende',
    4 => 'Ikwuano',
    5 => 'Isiala-Ngwa North',
    6 => 'Isiala-Ngwa South',
    7 => 'Isuikwato',
    8 => 'Obi Nwa',
    9 => 'Ohafia',
    10 => 'Osisioma',
    11 => 'Ngwa',
    12 => 'Ugwunagbo',
    13 => 'Ukwa East',
    14 => 'Ukwa West',
    15 => 'Umuahia North',
    16 => 'Umuahia South',
    17 => 'Umu-Neochi',
  ),
  'Adamawa' => 
  array (
    0 => 'Demsa',
    1 => 'Fufore',
    2 => 'Ganaye',
    3 => 'Gireri',
    4 => 'Gombi',
    5 => 'Guyuk',
    6 => 'Hong',
    7 => 'Jada',
    8 => 'Lamurde',
    9 => 'Madagali',
    10 => 'Maiha',
    11 => 'Mayo-Belwa',
    12 => 'Michika',
    13 => 'Mubi North',
    14 => 'Mubi South',
    15 => 'Numan',
    16 => 'Shelleng',
    17 => 'Song',
    18 => 'Toungo',
    19 => 'Yola North',
    20 => 'Yola South',
  ),
  'Anambra' => 
  array (
    0 => 'Aguata',
    1 => 'Anambra East',
    2 => 'Anambra West',
    3 => 'Anaocha',
    4 => 'Awka North',
    5 => 'Awka South',
    6 => 'Ayamelum',
    7 => 'Dunukofia',
    8 => 'Ekwusigo',
    9 => 'Idemili North',
    10 => 'Idemili south',
    11 => 'Ihiala',
    12 => 'Njikoka',
    13 => 'Nnewi North',
    14 => 'Nnewi South',
    15 => 'Ogbaru',
    16 => 'Onitsha North',
    17 => 'Onitsha South',
    18 => 'Orumba North',
    19 => 'Orumba South',
    20 => 'Oyi',
  ),
  'Akwa Ibom' => 
  array (
    0 => 'Abak',
    1 => 'Eastern Obolo',
    2 => 'Eket',
    3 => 'Esit Eket',
    4 => 'Essien Udim',
    5 => 'Etim Ekpo',
    6 => 'Etinan',
    7 => 'Ibeno',
    8 => 'Ibesikpo Asutan',
    9 => 'Ibiono Ibom',
    10 => 'Ika',
    11 => 'Ikono',
    12 => 'Ikot Abasi',
    13 => 'Ikot Ekpene',
    14 => 'Ini',
    15 => 'Itu',
    16 => 'Mbo',
    17 => 'Mkpat Enin',
    18 => 'Nsit Atai',
    19 => 'Nsit Ibom',
    20 => 'Nsit Ubium',
    21 => 'Obot Akara',
    22 => 'Okobo',
    23 => 'Onna',
    24 => 'Oron',
    25 => 'Oruk Anam',
    26 => 'Udung Uko',
    27 => 'Ukanafun',
    28 => 'Uruan',
    29 => 'Urue-Offong/Oruko ',
    30 => 'Uyo',
  ),
  'Bauchi' => 
  array (
    0 => 'Alkaleri',
    1 => 'Bauchi',
    2 => 'Bogoro',
    3 => 'Damban',
    4 => 'Darazo',
    5 => 'Dass',
    6 => 'Ganjuwa',
    7 => 'Giade',
    8 => 'Itas/Gadau',
    9 => 'Jama\'are',
    10 => 'Katagum',
    11 => 'Kirfi',
    12 => 'Misau',
    13 => 'Ningi',
    14 => 'Shira',
    15 => 'Tafawa-Balewa',
    16 => 'Toro',
    17 => 'Warji',
    18 => 'Zaki',
  ),
  'Bayelsa' => 
  array (
    0 => 'Brass',
    1 => 'Ekeremor',
    2 => 'Kolokuma/Opokuma',
    3 => 'Nembe',
    4 => 'Ogbia',
    5 => 'Sagbama',
    6 => 'Southern Jaw',
    7 => 'Yenegoa',
  ),
  'Benue' => 
  array (
    0 => 'Ado',
    1 => 'Agatu',
    2 => 'Apa',
    3 => 'Buruku',
    4 => 'Gboko',
    5 => 'Guma',
    6 => 'Gwer East',
    7 => 'Gwer West',
    8 => 'Katsina-Ala',
    9 => 'Konshisha',
    10 => 'Kwande',
    11 => 'Logo',
    12 => 'Makurdi',
    13 => 'Obi',
    14 => 'Ogbadibo',
    15 => 'Oju',
    16 => 'Okpokwu',
    17 => 'Ohimini',
    18 => 'Oturkpo',
    19 => 'Tarka',
    20 => 'Ukum',
    21 => 'Ushongo',
    22 => 'Vandeikya',
  ),
  'Borno' => 
  array (
    0 => 'Abadam',
    1 => 'Askira/Uba',
    2 => 'Bama',
    3 => 'Bayo',
    4 => 'Biu',
    5 => 'Chibok',
    6 => 'Damboa',
    7 => 'Dikwa',
    8 => 'Gubio',
    9 => 'Guzamala',
    10 => 'Gwoza',
    11 => 'Hawul',
    12 => 'Jere',
    13 => 'Kaga',
    14 => 'Kala/Balge',
    15 => 'Konduga',
    16 => 'Kukawa',
    17 => 'Kwaya Kusar',
    18 => 'Mafa',
    19 => 'Magumeri',
    20 => 'Maiduguri',
    21 => 'Marte',
    22 => 'Mobbar',
    23 => 'Monguno',
    24 => 'Ngala',
    25 => 'Nganzai',
    26 => 'Shani',
  ),
  'Cross River' => 
  array (
    0 => 'Akpabuyo',
    1 => 'Odukpani',
    2 => 'Akamkpa',
    3 => 'Biase',
    4 => 'Abi',
    5 => 'Ikom',
    6 => 'Yarkur',
    7 => 'Odubra',
    8 => 'Boki',
    9 => 'Ogoja',
    10 => 'Yala',
    11 => 'Obanliku',
    12 => 'Obudu',
    13 => 'Calabar South',
    14 => 'Etung',
    15 => 'Bekwara',
    16 => 'Bakassi',
    17 => 'Calabar Municipality',
  ),
  'Delta' => 
  array (
    0 => 'Oshimili',
    1 => 'Aniocha',
    2 => 'Aniocha South',
    3 => 'Ika South',
    4 => 'Ika North-East',
    5 => 'Ndokwa West',
    6 => 'Ndokwa East',
    7 => 'Isoko south',
    8 => 'Isoko North',
    9 => 'Bomadi',
    10 => 'Burutu',
    11 => 'Ughelli South',
    12 => 'Ughelli North',
    13 => 'Ethiope West',
    14 => 'Ethiope East',
    15 => 'Sapele',
    16 => 'Okpe',
    17 => 'Warri North',
    18 => 'Warri South',
    19 => 'Uvwie',
    20 => 'Udu',
    21 => 'Warri Central',
    22 => 'Ukwani',
    23 => 'Oshimili North',
    24 => 'Patani',
  ),
  'Ebonyi' => 
  array (
    0 => 'Edda',
    1 => 'Afikpo',
    2 => 'Onicha',
    3 => 'Ohaozara',
    4 => 'Abakaliki',
    5 => 'Ishielu',
    6 => 'lkwo',
    7 => 'Ezza',
    8 => 'Ezza South',
    9 => 'Ohaukwu',
    10 => 'Ebonyi',
    11 => 'Ivo',
  ),
  'Enugu' => 
  array (
    0 => 'Enugu South,',
    1 => 'Igbo-Eze South',
    2 => 'Enugu North',
    3 => 'Nkanu',
    4 => 'Udi Agwu',
    5 => 'Oji-River',
    6 => 'Ezeagu',
    7 => 'IgboEze North',
    8 => 'Isi-Uzo',
    9 => 'Nsukka',
    10 => 'Igbo-Ekiti',
    11 => 'Uzo-Uwani',
    12 => 'Enugu Eas',
    13 => 'Aninri',
    14 => 'Nkanu East',
    15 => 'Udenu.',
  ),
  'Edo' => 
  array (
    0 => 'Esan North-East',
    1 => 'Esan Central',
    2 => 'Esan West',
    3 => 'Egor',
    4 => 'Ukpoba',
    5 => 'Central',
    6 => 'Etsako Central',
    7 => 'Igueben',
    8 => 'Oredo',
    9 => 'Ovia SouthWest',
    10 => 'Ovia South-East',
    11 => 'Orhionwon',
    12 => 'Uhunmwonde',
    13 => 'Etsako East',
    14 => 'Esan South-East',
  ),
  'Ekiti' => 
  array (
    0 => 'Ado',
    1 => 'Ekiti-East',
    2 => 'Ekiti-West',
    3 => 'Emure/Ise/Orun',
    4 => 'Ekiti South-West',
    5 => 'Ikere',
    6 => 'Irepodun',
    7 => 'Ijero,',
    8 => 'Ido/Osi',
    9 => 'Oye',
    10 => 'Ikole',
    11 => 'Moba',
    12 => 'Gbonyin',
    13 => 'Efon',
    14 => 'Ise/Orun',
    15 => 'Ilejemeje.',
  ),
  'FCT' => 
  array (
    0 => 'Abaji',
    1 => 'Abuja Municipal',
    2 => 'Bwari',
    3 => 'Gwagwalada',
    4 => 'Kuje',
    5 => 'Kwali',
  ),
  'Gombe' => 
  array (
    0 => 'Akko',
    1 => 'Balanga',
    2 => 'Billiri',
    3 => 'Dukku',
    4 => 'Kaltungo',
    5 => 'Kwami',
    6 => 'Shomgom',
    7 => 'Funakaye',
    8 => 'Gombe',
    9 => 'Nafada/Bajoga',
    10 => 'Yamaltu/Delta.',
  ),
  'Imo' => 
  array (
    0 => 'Aboh-Mbaise',
    1 => 'Ahiazu-Mbaise',
    2 => 'Ehime-Mbano',
    3 => 'Ezinihitte',
    4 => 'Ideato North',
    5 => 'Ideato South',
    6 => 'Ihitte/Uboma',
    7 => 'Ikeduru',
    8 => 'Isiala Mbano',
    9 => 'Isu',
    10 => 'Mbaitoli',
    11 => 'Mbaitoli',
    12 => 'Ngor-Okpala',
    13 => 'Njaba',
    14 => 'Nwangele',
    15 => 'Nkwerre',
    16 => 'Obowo',
    17 => 'Oguta',
    18 => 'Ohaji/Egbema',
    19 => 'Okigwe',
    20 => 'Orlu',
    21 => 'Orsu',
    22 => 'Oru East',
    23 => 'Oru West',
    24 => 'Owerri-Municipal',
    25 => 'Owerri North',
    26 => 'Owerri West',
  ),
  'Jigawa' => 
  array (
    0 => 'Auyo',
    1 => 'Babura',
    2 => 'Birni Kudu',
    3 => 'Biriniwa',
    4 => 'Buji',
    5 => 'Dutse',
    6 => 'Gagarawa',
    7 => 'Garki',
    8 => 'Gumel',
    9 => 'Guri',
    10 => 'Gwaram',
    11 => 'Gwiwa',
    12 => 'Hadejia',
    13 => 'Jahun',
    14 => 'Kafin Hausa',
    15 => 'Kaugama Kazaure',
    16 => 'Kiri Kasamma',
    17 => 'Kiyawa',
    18 => 'Maigatari',
    19 => 'Malam Madori',
    20 => 'Miga',
    21 => 'Ringim',
    22 => 'Roni',
    23 => 'Sule-Tankarkar',
    24 => 'Taura',
    25 => 'Yankwashi',
  ),
  'Kaduna' => 
  array (
    0 => 'Birni-Gwari',
    1 => 'Chikun',
    2 => 'Giwa',
    3 => 'Igabi',
    4 => 'Ikara',
    5 => 'jaba',
    6 => 'Jema\'a',
    7 => 'Kachia',
    8 => 'Kaduna North',
    9 => 'Kaduna South',
    10 => 'Kagarko',
    11 => 'Kajuru',
    12 => 'Kaura',
    13 => 'Kauru',
    14 => 'Kubau',
    15 => 'Kudan',
    16 => 'Lere',
    17 => 'Makarfi',
    18 => 'Sabon-Gari',
    19 => 'Sanga',
    20 => 'Soba',
    21 => 'Zango-Kataf',
    22 => 'Zaria',
  ),
  'Kano' => 
  array (
    0 => 'Ajingi',
    1 => 'Albasu',
    2 => 'Bagwai',
    3 => 'Bebeji',
    4 => 'Bichi',
    5 => 'Bunkure',
    6 => 'Dala',
    7 => 'Dambatta',
    8 => 'Dawakin Kudu',
    9 => 'Dawakin Tofa',
    10 => 'Doguwa',
    11 => 'Fagge',
    12 => 'Gabasawa',
    13 => 'Garko',
    14 => 'Garum',
    15 => 'Mallam',
    16 => 'Gaya',
    17 => 'Gezawa',
    18 => 'Gwale',
    19 => 'Gwarzo',
    20 => 'Kabo',
    21 => 'Kano Municipal',
    22 => 'Karaye',
    23 => 'Kibiya',
    24 => 'Kiru',
    25 => 'kumbotso',
    26 => 'Ghari',
    27 => 'Kura',
    28 => 'Madobi',
    29 => 'Makoda',
    30 => 'Minjibir',
    31 => 'Nasarawa',
    32 => 'Rano',
    33 => 'Rimin Gado',
    34 => 'Rogo',
    35 => 'Shanono',
    36 => 'Sumaila',
    37 => 'Takali',
    38 => 'Tarauni',
    39 => 'Tofa',
    40 => 'Tsanyawa',
    41 => 'Tudun Wada',
    42 => 'Ungogo',
    43 => 'Warawa',
    44 => 'Wudil',
  ),
  'Katsina' => 
  array (
    0 => 'Bakori',
    1 => 'Batagarawa',
    2 => 'Batsari',
    3 => 'Baure',
    4 => 'Bindawa',
    5 => 'Charanchi',
    6 => 'Dandume',
    7 => 'Danja',
    8 => 'Dan Musa',
    9 => 'Daura',
    10 => 'Dutsi',
    11 => 'Dutsin-Ma',
    12 => 'Faskari',
    13 => 'Funtua',
    14 => 'Ingawa',
    15 => 'Jibia',
    16 => 'Kafur',
    17 => 'Kaita',
    18 => 'Kankara',
    19 => 'Kankia',
    20 => 'Katsina',
    21 => 'Kurfi',
    22 => 'Kusada',
    23 => 'Mai\'Adua',
    24 => 'Malumfashi',
    25 => 'Mani',
    26 => 'Mashi',
    27 => 'Matazuu',
    28 => 'Musawa',
    29 => 'Rimi',
    30 => 'Sabuwa',
    31 => 'Safana',
    32 => 'Sandamu',
    33 => 'Zango',
  ),
  'Kebbi' => 
  array (
    0 => 'Aleiro',
    1 => 'Arewa-Dandi',
    2 => 'Argungu',
    3 => 'Augie',
    4 => 'Bagudo',
    5 => 'Birnin Kebbi',
    6 => 'Bunza',
    7 => 'Dandi',
    8 => 'Fakai',
    9 => 'Gwandu',
    10 => 'Jega',
    11 => 'Kalgo',
    12 => 'Koko/Besse',
    13 => 'Maiyama',
    14 => 'Ngaski',
    15 => 'Sakaba',
    16 => 'Shanga',
    17 => 'Suru',
    18 => 'Wasagu/Danko',
    19 => 'Yauri',
    20 => 'Zuru',
  ),
  'Kogi' => 
  array (
    0 => 'Adavi',
    1 => 'Ajaokuta',
    2 => 'Ankpa',
    3 => 'Bassa',
    4 => 'Dekina',
    5 => 'Ibaji',
    6 => 'Idah',
    7 => 'Igalamela-Odolu',
    8 => 'Ijumu',
    9 => 'Kabba/Bunu',
    10 => 'Kogi',
    11 => 'Lokoja',
    12 => 'Mopa-Muro',
    13 => 'Ofu',
    14 => 'Ogori/Mangongo',
    15 => 'Okehi',
    16 => 'Okene',
    17 => 'Olamabolo',
    18 => 'Omala',
    19 => 'Yagba East',
    20 => 'Yagba West',
  ),
  'Kwara' => 
  array (
    0 => 'Asa',
    1 => 'Baruten',
    2 => 'Edu',
    3 => 'Ekiti',
    4 => 'Ifelodun',
    5 => 'Ilorin East',
    6 => 'Ilorin West',
    7 => 'Irepodun',
    8 => 'Isin',
    9 => 'Kaiama',
    10 => 'Moro',
    11 => 'Offa',
    12 => 'Oke-Ero',
    13 => 'Oyun',
    14 => 'Pategi',
  ),
  'Lagos' => 
  array (
    0 => 'Agege',
    1 => 'Ajeromi-Ifelodun',
    2 => 'Alimosho',
    3 => 'Amuwo-Odofin',
    4 => 'Apapa',
    5 => 'Badagry',
    6 => 'Epe',
    7 => 'Eti-Osa',
    8 => 'Ibeju/Lekki',
    9 => 'Ifako-Ijaye',
    10 => 'Ikeja',
    11 => 'Ikorodu',
    12 => 'Kosofe',
    13 => 'Lagos Island',
    14 => 'Lagos Mainland',
    15 => 'Mushin',
    16 => 'Ojo',
    17 => 'Oshodi-Isolo',
    18 => 'Shomolu',
    19 => 'Surulere',
  ),
  'Nasarawa' => 
  array (
    0 => 'Akwanga',
    1 => 'Awe',
    2 => 'Doma',
    3 => 'Karu',
    4 => 'Keana',
    5 => 'Keffi',
    6 => 'Kokona',
    7 => 'Lafia',
    8 => 'Nasarawa',
    9 => 'Nasarawa-Eggon',
    10 => 'Obi',
    11 => 'Toto',
    12 => 'Wamba',
  ),
  'Niger' => 
  array (
    0 => 'Agaie',
    1 => 'Agwara',
    2 => 'Bida',
    3 => 'Borgu',
    4 => 'Bosso',
    5 => 'Chanchaga',
    6 => 'Edati',
    7 => 'Gbako',
    8 => 'Gurara',
    9 => 'Katcha',
    10 => 'Kontagora',
    11 => 'Lapai',
    12 => 'Lavun',
    13 => 'Magama',
    14 => 'Mariga',
    15 => 'Mashegu',
    16 => 'Mokwa',
    17 => 'Muya',
    18 => 'Pailoro',
    19 => 'Rafi',
    20 => 'Rijau',
    21 => 'Shiroro',
    22 => 'Suleja',
    23 => 'Tafa',
    24 => 'Wushishi',
  ),
  'Ogun' => 
  array (
    0 => 'Abeokuta North',
    1 => 'Abeokuta South',
    2 => 'Ado-Odo/Ota',
    3 => 'Yewa North',
    4 => 'Yewa South',
    5 => 'Ewekoro',
    6 => 'Ifo',
    7 => 'Ijebu East',
    8 => 'Ijebu North',
    9 => 'Ijebu North East',
    10 => 'Ijebu Ode',
    11 => 'Ikenne',
    12 => 'Imeko-Afon',
    13 => 'Ipokia',
    14 => 'Obafemi-Owode',
    15 => 'Ogun Waterside',
    16 => 'Odeda',
    17 => 'Odogbolu',
    18 => 'Remo North',
    19 => 'Shagamu',
  ),
  'Ondo' => 
  array (
    0 => 'Akoko North East',
    1 => 'Akoko North West',
    2 => 'Akoko South Akure East',
    3 => 'Akoko South West',
    4 => 'Akure North',
    5 => 'Akure South',
    6 => 'Ese-Odo',
    7 => 'Idanre',
    8 => 'Ifedore',
    9 => 'Ilaje',
    10 => 'Ile-Oluji',
    11 => 'Okeigbo',
    12 => 'Irele',
    13 => 'Odigbo',
    14 => 'Okitipupa',
    15 => 'Ondo East',
    16 => 'Ondo West',
    17 => 'Ose',
    18 => 'Owo',
  ),
  'Osun' => 
  array (
    0 => 'Aiyedade',
    1 => 'Aiyedire',
    2 => 'Atakumosa East',
    3 => 'Atakumosa West',
    4 => 'Boluwaduro',
    5 => 'Boripe',
    6 => 'Ede North',
    7 => 'Ede South',
    8 => 'Egbedore',
    9 => 'Ejigbo',
    10 => 'Ife Central',
    11 => 'Ife East',
    12 => 'Ife North',
    13 => 'Ife South',
    14 => 'Ifedayo',
    15 => 'Ifelodun',
    16 => 'Ila',
    17 => 'Ilesha East',
    18 => 'Ilesha West',
    19 => 'Irepodun',
    20 => 'Irewole',
    21 => 'Isokan',
    22 => 'Iwo',
    23 => 'Obokun',
    24 => 'Odo-Otin',
    25 => 'Ola-Oluwa',
    26 => 'Olorunda',
    27 => 'Oriade',
    28 => 'Orolu',
    29 => 'Osogbo',
  ),
  'Oyo' => 
  array (
    0 => 'Afijio',
    1 => 'Akinyele',
    2 => 'Atiba',
    3 => 'Atisbo',
    4 => 'Egbeda',
    5 => 'Ibadan Central',
    6 => 'Ibadan North',
    7 => 'Ibadan North West',
    8 => 'Ibadan South East',
    9 => 'Ibadan South West',
    10 => 'Ibarapa Central',
    11 => 'Ibarapa East',
    12 => 'Ibarapa North',
    13 => 'Ido',
    14 => 'Irepo',
    15 => 'Iseyin',
    16 => 'Itesiwaju',
    17 => 'Iwajowa',
    18 => 'Kajola',
    19 => 'Lagelu Ogbomosho North',
    20 => 'Ogbomosho South',
    21 => 'Ogo Oluwa',
    22 => 'Olorunsogo',
    23 => 'Oluyole',
    24 => 'Ona-Ara',
    25 => 'Orelope',
    26 => 'Ori Ire',
    27 => 'Oyo East',
    28 => 'Oyo West',
    29 => 'Saki East',
    30 => 'Saki West',
    31 => 'Surulere',
  ),
  'Plateau' => 
  array (
    0 => 'Barikin Ladi',
    1 => 'Bassa',
    2 => 'Bokkos',
    3 => 'Jos East',
    4 => 'Jos North',
    5 => 'Jos South',
    6 => 'Kanam',
    7 => 'Kanke',
    8 => 'Langtang North',
    9 => 'Langtang South',
    10 => 'Mangu',
    11 => 'Mikang',
    12 => 'Pankshin',
    13 => 'Qua\'an Pan',
    14 => 'Riyom',
    15 => 'Shendam',
    16 => 'Wase',
  ),
  'Rivers' => 
  array (
    0 => 'Abua/Odual',
    1 => 'Ahoada East',
    2 => 'Ahoada West',
    3 => 'Akuku Toru',
    4 => 'Andoni',
    5 => 'Asari-Toru',
    6 => 'Bonny',
    7 => 'Degema',
    8 => 'Emohua',
    9 => 'Eleme',
    10 => 'Etche',
    11 => 'Gokana',
    12 => 'Ikwerre',
    13 => 'Khana',
    14 => 'Obio/Akpor',
    15 => 'Ogba/Egbema/Ndoni',
    16 => 'Ogu/Bolo',
    17 => 'Okrika',
    18 => 'Omumma',
    19 => 'Opobo/Nkoro',
    20 => 'Oyigbo',
    21 => 'Port-Harcourt',
    22 => 'Tai',
  ),
  'Sokoto' => 
  array (
    0 => 'Binji',
    1 => 'Bodinga',
    2 => 'Dange-shnsi',
    3 => 'Gada',
    4 => 'Goronyo',
    5 => 'Gudu',
    6 => 'Gawabawa',
    7 => 'Illela',
    8 => 'Isa',
    9 => 'Kware',
    10 => 'kebbe',
    11 => 'Rabah',
    12 => 'Sabon birni',
    13 => 'Shagari',
    14 => 'Silame',
    15 => 'Sokoto North',
    16 => 'Sokoto South',
    17 => 'Tambuwal',
    18 => 'Tqngaza',
    19 => 'Tureta',
    20 => 'Wamako',
    21 => 'Wurno',
    22 => 'Yabo',
  ),
  'Taraba' => 
  array (
    0 => 'Ardo-kola',
    1 => 'Bali',
    2 => 'Donga',
    3 => 'Gashaka',
    4 => 'Cassol',
    5 => 'Ibi',
    6 => 'Jalingo',
    7 => 'Karin-Lamido',
    8 => 'Kurmi',
    9 => 'Lau',
    10 => 'Sardauna',
    11 => 'Takum',
    12 => 'Ussa',
    13 => 'Wukari',
    14 => 'Yorro',
    15 => 'Zing',
  ),
  'Yobe' => 
  array (
    0 => 'Bade',
    1 => 'Bursari',
    2 => 'Damaturu',
    3 => 'Fika',
    4 => 'Fune',
    5 => 'Geidam',
    6 => 'Gujba',
    7 => 'Gulani',
    8 => 'Jakusko',
    9 => 'Karasuwa',
    10 => 'Karawa',
    11 => 'Machina',
    12 => 'Nangere',
    13 => 'Nguru Potiskum',
    14 => 'Tarmua',
    15 => 'Yunusari',
    16 => 'Yusufari',
  ),
  'Zamfara' => 
  array (
    0 => 'Anka',
    1 => 'Bakura',
    2 => 'Birnin Magaji',
    3 => 'Bukkuyum',
    4 => 'Bungudu',
    5 => 'Gummi',
    6 => 'Gusau',
    7 => 'Kaura',
    8 => 'Namoda',
    9 => 'Maradun',
    10 => 'Maru',
    11 => 'Shinkafi',
    12 => 'Talata Mafara',
    13 => 'Tsafe',
    14 => 'Zurmi',
  ),
);

        foreach ($map as $stateName => $cities) {
            $state = State::query()->where('name', $stateName)->first();
            if (! $state) {
                continue;
            }

            foreach (array_unique($cities) as $city) {
                $name = trim((string) $city, " \t\n\r\0\x0B.,");
                if ($name === '') {
                    continue;
                }

                City::query()->updateOrCreate(
                    ['state_id' => $state->id, 'name' => Str::title($name)],
                    []
                );
            }
        }
    }
}
