<?php

use App\Http\Controllers\Api\V1\Admin\AdminAssociationGovernanceController;
use App\Http\Controllers\Api\V1\Admin\AdminAssociationOfficerController;
use App\Http\Controllers\Api\V1\Admin\AdminBoardReportController;
use App\Http\Controllers\Api\V1\Admin\AdminDashboardController;
use App\Http\Controllers\Api\V1\Admin\AdminDocumentController;
use App\Http\Controllers\Api\V1\Admin\AdminFinanceAdjustmentController;
use App\Http\Controllers\Api\V1\Admin\AdminFinanceSummaryController;
use App\Http\Controllers\Api\V1\Admin\AdminImportController;
use App\Http\Controllers\Api\V1\Admin\AdminInstitutionAnnualDeclarationController;
use App\Http\Controllers\Api\V1\Admin\AdminInstitutionController;
use App\Http\Controllers\Api\V1\Admin\AdminInvoiceController;
use App\Http\Controllers\Api\V1\Admin\AdminLicenceController;
use App\Http\Controllers\Api\V1\Admin\AdminLicensingFeePlanController;
use App\Http\Controllers\Api\V1\Admin\AdminMemberApplicationController;
use App\Http\Controllers\Api\V1\Admin\AdminMemberWorkImportSettingsController;
use App\Http\Controllers\Api\V1\Admin\AdminMemberController;
use App\Http\Controllers\Api\V1\Admin\AdminPaymentController;
use App\Http\Controllers\Api\V1\Admin\AdminPushNotificationController;
use App\Http\Controllers\Api\V1\Admin\AdminReportController;
use App\Http\Controllers\Api\V1\Admin\AdminSupportTicketController;
use App\Http\Controllers\Api\V1\Admin\AdminTermsAndConditionController;
use App\Http\Controllers\Api\V1\Admin\AdminTimelineController;
use App\Http\Controllers\Api\V1\Admin\AdminUsageDeclarationController;
use App\Http\Controllers\Api\V1\Admin\AdminWipoConnectOutboxController;
use App\Http\Controllers\Api\V1\Admin\AdminWorkController;
use App\Http\Controllers\Api\V1\Admin\AdminWorkReviewController;
use App\Http\Controllers\Api\V1\Admin\AuditLogController;
use App\Http\Controllers\Api\V1\Association\ApplicationReviewController;
use App\Http\Controllers\Api\V1\Association\AssociationDashboardController;
use App\Http\Controllers\Api\V1\Association\AssociationLogoController;
use App\Http\Controllers\Api\V1\Association\AssociationProfileController;
use App\Http\Controllers\Api\V1\Auth\AuthController;
use App\Http\Controllers\Api\V1\Auth\AvatarController;
use App\Http\Controllers\Api\V1\Auth\EmailVerificationController;
use App\Http\Controllers\Api\V1\Auth\MeController;
use App\Http\Controllers\Api\V1\Auth\NotificationController;
use App\Http\Controllers\Api\V1\Auth\NotificationPreferenceController;
use App\Http\Controllers\Api\V1\Auth\PasswordResetController;
use App\Http\Controllers\Api\V1\Auth\SecurityActivityController;
use App\Http\Controllers\Api\V1\Auth\TwoFactorController;
use App\Http\Controllers\Api\V1\Institution\InstitutionAnnualDeclarationController;
use App\Http\Controllers\Api\V1\Institution\InstitutionDashboardController;
use App\Http\Controllers\Api\V1\Institution\InstitutionDocumentController;
use App\Http\Controllers\Api\V1\Institution\InstitutionInvoiceController;
use App\Http\Controllers\Api\V1\Institution\InstitutionLicenceController;
use App\Http\Controllers\Api\V1\Institution\InstitutionLogoController;
use App\Http\Controllers\Api\V1\Institution\InstitutionPaymentController;
use App\Http\Controllers\Api\V1\Institution\InstitutionProfileController;
use App\Http\Controllers\Api\V1\Institution\UsageDeclarationController as InstitutionUsageDeclarationController;
use App\Http\Controllers\Api\V1\Member\MemberApplicationController;
use App\Http\Controllers\Api\V1\Member\MemberApplicationDocumentController;
use App\Http\Controllers\Api\V1\Member\MemberProfileController;
use App\Http\Controllers\Api\V1\Member\MemberWorkImportController;
use App\Http\Controllers\Api\V1\Member\WorkContributorController;
use App\Http\Controllers\Api\V1\Member\WorkController;
use App\Http\Controllers\Api\V1\Member\WorkFileController;
use App\Http\Controllers\Api\V1\Public\AssociationController as PublicAssociationController;
use App\Http\Controllers\Api\V1\Public\LanguageController as PublicLanguageController;
use App\Http\Controllers\Api\V1\Public\LicenceLookupController;
use App\Http\Controllers\Api\V1\Public\LocationController;
use App\Http\Controllers\Api\V1\Public\PlatformContentController;
use App\Http\Controllers\Api\V1\Super\AdminPinController;
use App\Http\Controllers\Api\V1\Super\AssociationManagementController;
use App\Http\Controllers\Api\V1\Super\LanguageController as SuperLanguageController;
use App\Http\Controllers\Api\V1\Super\RolePermissionController;
use App\Http\Controllers\Api\V1\Super\SettingController;
use App\Http\Controllers\Api\V1\Super\SuperDashboardController;
use App\Http\Controllers\Api\V1\Super\SuperIntegrationController;
use App\Http\Controllers\Api\V1\Super\SuperTimelineController;
use App\Http\Controllers\Api\V1\Super\UserManagementController;
use App\Http\Controllers\Api\V1\Support\SupportTicketController;
use App\Http\Controllers\Api\V1\Webhooks\PaymentWebhookController;
use App\Http\Controllers\Api\V1\Webhooks\WipoConnectWebhookController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('payments/webhook', [PaymentWebhookController::class, 'handle']);
    Route::post('webhooks/wipo-connect', [WipoConnectWebhookController::class, 'handle'])->middleware('throttle:120,1');

    Route::post('auth/register-member', [AuthController::class, 'registerMember']);
    Route::post('auth/member-registration/verify-otp', [AuthController::class, 'verifyMemberOtp'])->middleware('throttle:email-verification');
    Route::post('auth/member-registration/resend-otp', [AuthController::class, 'resendMemberOtp'])->middleware('throttle:email-verification');
    Route::post('auth/register-institution', [AuthController::class, 'registerInstitution']);
    Route::post('auth/institution-registration/verify-otp', [AuthController::class, 'verifyInstitutionOtp'])->middleware('throttle:email-verification');
    Route::post('auth/institution-registration/resend-otp', [AuthController::class, 'resendInstitutionOtp'])->middleware('throttle:email-verification');
    Route::post('auth/login', [AuthController::class, 'login']);
    Route::post('auth/two-factor/verify', [TwoFactorController::class, 'verifyLogin']);
    Route::post('auth/forgot-password', [PasswordResetController::class, 'forgotPassword'])->middleware('throttle:password-reset');
    Route::post('auth/reset-password', [PasswordResetController::class, 'resetPassword'])->middleware('throttle:password-reset');
    Route::post('auth/verify-reset-token', [PasswordResetController::class, 'verifyToken'])->middleware('throttle:password-reset');

    Route::get('associations', [PublicAssociationController::class, 'index']);
    Route::get('associations/{association}', [PublicAssociationController::class, 'show']);
    Route::get('locations/states', [LocationController::class, 'states']);
    Route::get('locations/states/{state}/cities', [LocationController::class, 'cities']);
    Route::get('licensing/lookup/{licenceId}', [LicenceLookupController::class, 'show']);
    Route::get('platform-settings', [PlatformContentController::class, 'settings']);
    Route::get('languages', [PublicLanguageController::class, 'index']);
    Route::get('terms-and-conditions/active', [PlatformContentController::class, 'terms']);
    Route::post('licensing/payments/initialize', [LicenceLookupController::class, 'initializePayment']);
});

Route::prefix('v1')->middleware(['auth:sanctum'])->group(function () {
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('me', [MeController::class, 'show']);
    Route::patch('me', [MeController::class, 'update']);
    Route::patch('me/change-password', [MeController::class, 'changePassword']);
    Route::get('me/dashboard-summary', [MeController::class, 'dashboardSummary']);
    Route::post('me/avatar', [AvatarController::class, 'store']);
    Route::delete('me/avatar', [AvatarController::class, 'destroy']);
    Route::get('me/two-factor', [TwoFactorController::class, 'status']);
    Route::post('me/two-factor/enable', [TwoFactorController::class, 'enable']);
    Route::post('me/two-factor/disable', [TwoFactorController::class, 'disable']);
    Route::post('me/security/confirm', [TwoFactorController::class, 'confirmSensitive']);
    Route::get('me/security-activity', [SecurityActivityController::class, 'index']);
    Route::get('me/notification-preferences', [NotificationPreferenceController::class, 'index']);
    Route::put('me/notification-preferences', [NotificationPreferenceController::class, 'update']);
    Route::get('me/notifications', [NotificationController::class, 'index']);
    Route::get('me/notifications/unread-count', [NotificationController::class, 'unreadCount']);
    Route::post('me/notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::post('me/notifications/{notification}/read', [NotificationController::class, 'markRead']);

    Route::get('email/verify', [EmailVerificationController::class, 'notice']);
    Route::get('email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware(['signed', 'throttle:email-verification'])->name('verification.verify');
    Route::post('email/verification-notification', [EmailVerificationController::class, 'resend'])->middleware('throttle:email-verification');
});

Route::prefix('v1')->middleware(['auth:sanctum', 'verified', 'role:member|association_officer|institution_user'])->group(function () {
    Route::get('support-tickets', [SupportTicketController::class, 'index'])->middleware('throttle:120,1');
    Route::post('support-tickets', [SupportTicketController::class, 'store'])->middleware('throttle:8,1');
    Route::get('support-tickets/{supportTicket}', [SupportTicketController::class, 'show'])->middleware('throttle:120,1');
    Route::post('support-tickets/{supportTicket}/replies', [SupportTicketController::class, 'storeReply'])->middleware('throttle:40,1');
});

Route::prefix('v1')->middleware(['auth:sanctum', 'verified', 'role:member'])->group(function () {
    Route::post('member-applications', [MemberApplicationController::class, 'store']);
    Route::get('member-applications/me', [MemberApplicationController::class, 'myApplication']);
    Route::get('member-applications/{memberApplication}', [MemberApplicationController::class, 'show']);
    Route::patch('member-applications/{memberApplication}', [MemberApplicationController::class, 'update']);
    Route::post('member-applications/{memberApplication}/submit', [MemberApplicationController::class, 'submit']);
    Route::get('member-applications/{memberApplication}/mandate', [MemberApplicationController::class, 'downloadMandate']);
    Route::post('member-applications/{memberApplication}/documents', [MemberApplicationDocumentController::class, 'store']);
    Route::delete('member-applications/{memberApplication}/documents/{document}', [MemberApplicationDocumentController::class, 'destroy']);
    Route::get('member/profile', [MemberProfileController::class, 'show']);
    Route::patch('member/profile', [MemberProfileController::class, 'update']);
    Route::get('works', [WorkController::class, 'index']);
    Route::post('works', [WorkController::class, 'store']);
    Route::get('works/{work}', [WorkController::class, 'show']);
    Route::patch('works/{work}', [WorkController::class, 'update']);
    Route::delete('works/{work}', [WorkController::class, 'destroy']);
    Route::post('works/{work}/request-update', [WorkController::class, 'requestUpdate']);
    Route::post('works/{work}/submit', [WorkController::class, 'submit']);
    Route::post('works/{work}/contributors', [WorkContributorController::class, 'store']);
    Route::patch('works/{work}/contributors/{contributor}', [WorkContributorController::class, 'update']);
    Route::delete('works/{work}/contributors/{contributor}', [WorkContributorController::class, 'destroy']);
    Route::post('works/{work}/files', [WorkFileController::class, 'store']);
    Route::delete('works/{work}/files/{file}', [WorkFileController::class, 'destroy']);

    $memberWorkImportUploadsPerHour = (int) config('member_work_imports.uploads_per_hour', 5);
    $memberWorkImportSubmitPerHour = (int) config('member_work_imports.submit_ready_per_hour', 1);

    Route::middleware('member_work_import.enabled')->group(function () use ($memberWorkImportUploadsPerHour, $memberWorkImportSubmitPerHour) {
        Route::get('work-import-batches/template', [MemberWorkImportController::class, 'template']);
        Route::get('work-import-batches/column-reference', [MemberWorkImportController::class, 'columnReference']);
        Route::get('work-import-batches', [MemberWorkImportController::class, 'index']);
        Route::post('work-import-batches', [MemberWorkImportController::class, 'store'])->middleware('throttle:'.$memberWorkImportUploadsPerHour.',60');
        Route::get('work-import-batches/{workImportBatch}', [MemberWorkImportController::class, 'show']);
        Route::get('work-import-batches/{workImportBatch}/failures', [MemberWorkImportController::class, 'failures']);
        Route::get('work-import-batches/{workImportBatch}/items', [MemberWorkImportController::class, 'items']);
        Route::get('work-import-batches/{workImportBatch}/error-report', [MemberWorkImportController::class, 'errorReport']);
        Route::post('work-import-batches/{workImportBatch}/process', [MemberWorkImportController::class, 'process']);
        Route::post('work-import-batches/{workImportBatch}/files', [MemberWorkImportController::class, 'uploadFiles']);
        Route::post('work-import-batches/{workImportBatch}/submit-ready', [MemberWorkImportController::class, 'submitReady'])->middleware('throttle:'.$memberWorkImportSubmitPerHour.',60');
    });
});

Route::prefix('v1/association')->middleware(['auth:sanctum', 'verified', 'role:association_officer'])->group(function () {
    Route::get('dashboard', [AssociationDashboardController::class, 'show']);
    Route::get('profile', [AssociationProfileController::class, 'show']);
    Route::patch('profile', [AssociationProfileController::class, 'update']);
    Route::post('logo', [AssociationLogoController::class, 'store']);
    Route::delete('logo', [AssociationLogoController::class, 'destroy']);
    Route::get('applications', [ApplicationReviewController::class, 'index']);
    Route::get('applications/{memberApplication}', [ApplicationReviewController::class, 'show']);
    Route::post('applications/{memberApplication}/validate-affiliation', [ApplicationReviewController::class, 'approve']);
    Route::post('applications/{memberApplication}/reject-affiliation', [ApplicationReviewController::class, 'reject']);
});

Route::prefix('v1/institution')->middleware(['auth:sanctum', 'verified', 'role:institution_user'])->group(function () {
    Route::get('profile', [InstitutionProfileController::class, 'show']);
    Route::post('licensing-terms/acceptance', [InstitutionProfileController::class, 'acceptLicensingTerms']);
    Route::patch('profile', [InstitutionProfileController::class, 'update']);
    Route::post('logo', [InstitutionLogoController::class, 'store']);
    Route::delete('logo', [InstitutionLogoController::class, 'destroy']);
    Route::post('documents', [InstitutionDocumentController::class, 'store']);
    Route::get('dashboard', [InstitutionDashboardController::class, 'show']);
    Route::get('declarations', [InstitutionAnnualDeclarationController::class, 'index']);
    Route::post('declarations', [InstitutionAnnualDeclarationController::class, 'store']);
    Route::get('declarations/{declaration}', [InstitutionAnnualDeclarationController::class, 'show']);
    Route::patch('declarations/{declaration}', [InstitutionAnnualDeclarationController::class, 'update']);
    Route::post('declarations/{declaration}/submit', [InstitutionAnnualDeclarationController::class, 'submit']);
    Route::get('licences', [InstitutionLicenceController::class, 'index']);
    Route::get('licences/{licence}/certificate', [InstitutionLicenceController::class, 'certificate']);
    Route::get('licences/{licence}', [InstitutionLicenceController::class, 'show']);
    Route::post('licences/{licence}/payments/initiate', [InstitutionPaymentController::class, 'initiate']);
    Route::get('licences/{licence}/payments', [InstitutionPaymentController::class, 'index']);
    Route::get('payments/{payment}/receipt', [InstitutionPaymentController::class, 'receipt']);
    Route::post('payments/{payment}/verify', [InstitutionPaymentController::class, 'verify']);
    Route::get('invoices', [InstitutionInvoiceController::class, 'index']);
    Route::get('invoices/{invoice}', [InstitutionInvoiceController::class, 'show']);
    Route::post('invoices/{invoice}/payments/initiate', [InstitutionInvoiceController::class, 'initiatePayment']);
    Route::post('invoices/{invoice}/offline-payments', [InstitutionInvoiceController::class, 'submitOfflinePayment']);
    Route::post('licences/{licence}/usage-declarations', [InstitutionUsageDeclarationController::class, 'store']);
    Route::get('usage-declarations', [InstitutionUsageDeclarationController::class, 'index']);
    Route::get('usage-declarations/{usageDeclaration}', [InstitutionUsageDeclarationController::class, 'show']);
});

Route::prefix('v1/admin')->middleware(['auth:sanctum', 'verified', 'role:admin|super_admin'])->group(function () {
    Route::get('support-tickets', [AdminSupportTicketController::class, 'index'])->middleware('throttle:120,1');
    Route::get('support-tickets/{supportTicket}', [AdminSupportTicketController::class, 'show'])->middleware('throttle:120,1');
    Route::patch('support-tickets/{supportTicket}', [AdminSupportTicketController::class, 'update'])->middleware('throttle:60,1');
    Route::post('support-tickets/{supportTicket}/replies', [AdminSupportTicketController::class, 'storeReply'])->middleware('throttle:60,1');
    Route::post('support-tickets/{supportTicket}/internal-notes', [AdminSupportTicketController::class, 'storeInternalNote'])->middleware('throttle:60,1');

    Route::get('dashboard/summary', [AdminDashboardController::class, 'summary']);
    Route::get('finance/summary', AdminFinanceSummaryController::class);
    Route::get('member-applications', [AdminMemberApplicationController::class, 'index']);
    Route::get('member-applications/{memberApplication}', [AdminMemberApplicationController::class, 'show']);
    Route::post('member-applications/{memberApplication}/approve', [AdminMemberApplicationController::class, 'approve']);
    Route::post('member-applications/{memberApplication}/request-changes', [AdminMemberApplicationController::class, 'requestChanges']);
    Route::post('member-applications/{memberApplication}/reject', [AdminMemberApplicationController::class, 'reject']);
    Route::delete('member-applications/{memberApplication}', [AdminMemberApplicationController::class, 'destroy'])->middleware('security.confirmed');
    Route::get('members', [AdminMemberController::class, 'index']);
    Route::get('members/export', [AdminMemberController::class, 'export']);
    Route::get('members/{member}', [AdminMemberController::class, 'show']);
    Route::delete('members/{member}', [AdminMemberController::class, 'destroy'])->middleware('security.confirmed');
    Route::get('works', [AdminWorkController::class, 'index']);
    Route::get('works/bulk-import-settings', [AdminMemberWorkImportSettingsController::class, 'show']);
    Route::put('works/bulk-import-settings', [AdminMemberWorkImportSettingsController::class, 'update']);
    Route::get('works/export', [AdminWorkController::class, 'export']);
    Route::get('works/{work}', [AdminWorkController::class, 'show']);
    Route::delete('works/{work}', [AdminWorkController::class, 'destroy'])->middleware('security.confirmed');
    Route::get('works/{work}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'indexForWork']);
    Route::post('works/{work}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'enqueueWork'])->middleware('security.confirmed');
    Route::get('institutions/{institution}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'indexForInstitution']);
    Route::post('institutions/{institution}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'enqueueInstitution'])->middleware('security.confirmed');
    Route::get('members/{member}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'indexForMember']);
    Route::post('members/{member}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'enqueueMember'])->middleware('security.confirmed');
    Route::get('licences/{licence}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'indexForLicence']);
    Route::post('licences/{licence}/wipo-connect/outbox', [AdminWipoConnectOutboxController::class, 'enqueueLicence'])->middleware('security.confirmed');
    Route::post('works/{work}/review', [AdminWorkReviewController::class, 'review'])->middleware('security.confirmed');
    Route::post('works/{work}/update-request/review', [AdminWorkReviewController::class, 'reviewUpdateRequest'])->middleware('security.confirmed');
    Route::post('works/{work}/contributors/{contributor}/dispute', [AdminWorkReviewController::class, 'disputeContributor'])->middleware('security.confirmed');
    Route::get('institutions', [AdminInstitutionController::class, 'index']);
    Route::get('institutions/export', [AdminInstitutionController::class, 'export']);
    Route::get('institutions/{institution}', [AdminInstitutionController::class, 'show']);
    Route::post('institutions/{institution}/approve', [AdminInstitutionController::class, 'approve'])->middleware('security.confirmed');
    Route::post('institutions/{institution}/reject', [AdminInstitutionController::class, 'reject'])->middleware('security.confirmed');
    Route::post('institutions/{institution}/deactivate', [AdminInstitutionController::class, 'deactivate'])->middleware('security.confirmed');
    Route::post('institutions/{institution}/reactivate', [AdminInstitutionController::class, 'reactivate'])->middleware('security.confirmed');
    Route::get('institution-declarations', [AdminInstitutionAnnualDeclarationController::class, 'index']);
    Route::get('institution-declarations/export', [AdminInstitutionAnnualDeclarationController::class, 'export']);
    Route::get('declarations/export', [AdminInstitutionAnnualDeclarationController::class, 'export']);
    Route::get('institution-declarations/{declaration}', [AdminInstitutionAnnualDeclarationController::class, 'show']);
    Route::post('institution-declarations/{declaration}/review', [AdminInstitutionAnnualDeclarationController::class, 'moveToReview'])->middleware('security.confirmed');
    Route::post('institution-declarations/{declaration}/approve', [AdminInstitutionAnnualDeclarationController::class, 'approve'])->middleware('security.confirmed');
    Route::post('institution-declarations/{declaration}/reject', [AdminInstitutionAnnualDeclarationController::class, 'reject'])->middleware('security.confirmed');
    Route::get('licensing/fee-plans', [AdminLicensingFeePlanController::class, 'index']);
    Route::post('licensing/fee-plans', [AdminLicensingFeePlanController::class, 'store']);
    Route::patch('licensing/fee-plans/{licensingFeePlan}', [AdminLicensingFeePlanController::class, 'update']);
    Route::get('licences', [AdminLicenceController::class, 'index']);
    Route::get('licences/export', [AdminLicenceController::class, 'export']);
    Route::get('licences/{licence}', [AdminLicenceController::class, 'show']);
    Route::get('payments', [AdminPaymentController::class, 'index']);
    Route::get('payments/export', [AdminPaymentController::class, 'export']);
    Route::get('payments/{payment}', [AdminPaymentController::class, 'show']);
    Route::post('notifications/push', [AdminPushNotificationController::class, 'store'])->middleware('security.confirmed');
    Route::get('payments/{payment}/offline-proof', [AdminPaymentController::class, 'downloadOfflineProof']);
    Route::post('payments/{payment}/offline/confirm', [AdminPaymentController::class, 'confirmOffline'])->middleware('security.confirmed');
    Route::post('payments/{payment}/offline/reject', [AdminPaymentController::class, 'rejectOffline'])->middleware('security.confirmed');
    Route::get('invoices', [AdminInvoiceController::class, 'index']);
    Route::get('invoices/{invoice}', [AdminInvoiceController::class, 'show']);
    Route::post('invoices/{invoice}/adjustments', [AdminFinanceAdjustmentController::class, 'store'])->middleware('security.confirmed');
    Route::get('associations', [AdminAssociationGovernanceController::class, 'index']);
    Route::get('associations/export', [AdminAssociationGovernanceController::class, 'export']);
    Route::get('associations/{association}', [AdminAssociationGovernanceController::class, 'show']);
    Route::post('associations/{association}/disable', [AdminAssociationGovernanceController::class, 'disable'])->middleware('security.confirmed');
    Route::post('associations/{association}/enable', [AdminAssociationGovernanceController::class, 'enable'])->middleware('security.confirmed');
    Route::post('associations/{association}/logo', [AdminAssociationGovernanceController::class, 'uploadLogo']);
    Route::get('associations/{association}/officers', [AdminAssociationOfficerController::class, 'index']);
    Route::patch('associations/{association}/officers/{user}', [AdminAssociationOfficerController::class, 'update'])
        ->middleware('security.confirmed');
    Route::get('usage-declarations', [AdminUsageDeclarationController::class, 'index']);
    Route::get('usage-declarations/{usageDeclaration}', [AdminUsageDeclarationController::class, 'show']);
    Route::get('reports/members', [AdminReportController::class, 'members']);
    Route::get('reports/works', [AdminReportController::class, 'works']);
    Route::get('reports/licences', [AdminReportController::class, 'licences']);
    Route::get('reports/completeness', [AdminReportController::class, 'completeness']);
    Route::get('audit-logs', [AuditLogController::class, 'index']);
    Route::get('audit-logs/{auditLog}', [AuditLogController::class, 'show']);
    Route::get('timelines/{entity}/{subjectId}', [AdminTimelineController::class, 'show']);
    Route::get('documents', [AdminDocumentController::class, 'index']);
    Route::post('documents', [AdminDocumentController::class, 'store']);
    Route::delete('documents/{document}', [AdminDocumentController::class, 'destroy']);
    Route::get('imports', [AdminImportController::class, 'index']);
    Route::post('imports', [AdminImportController::class, 'store']);
    Route::post('imports/{importBatch}/process', [AdminImportController::class, 'process'])->middleware('security.confirmed');
    Route::get('reports/board-summary', [AdminBoardReportController::class, 'summary']);
    Route::apiResource('terms-and-conditions', AdminTermsAndConditionController::class);
});

Route::prefix('v1/super')->middleware(['auth:sanctum', 'verified', 'role:super_admin'])->group(function () {
    Route::get('dashboard/summary', [SuperDashboardController::class, 'summary']);
    Route::get('associations', [AssociationManagementController::class, 'index']);
    Route::post('associations', [AssociationManagementController::class, 'store']);
    Route::get('associations/{association}', [AssociationManagementController::class, 'show']);
    Route::patch('associations/{association}', [AssociationManagementController::class, 'update']);
    Route::delete('associations/{association}', [AssociationManagementController::class, 'destroy']);
    Route::post('associations/{association}/activate', [AssociationManagementController::class, 'activate']);
    Route::post('associations/{association}/deactivate', [AssociationManagementController::class, 'deactivate']);
    Route::get('users', [UserManagementController::class, 'index']);
    Route::post('users', [UserManagementController::class, 'store']);
    Route::get('users/{user}', [UserManagementController::class, 'show']);
    Route::patch('users/{user}', [UserManagementController::class, 'update']);
    Route::post('users/{user}/activate', [UserManagementController::class, 'activate']);
    Route::post('users/{user}/deactivate', [UserManagementController::class, 'deactivate']);
    Route::get('timelines/{entity}/{subjectId}', [SuperTimelineController::class, 'show']);
    Route::get('roles', [RolePermissionController::class, 'roles']);
    Route::get('roles/{role}', [RolePermissionController::class, 'showRole']);
    Route::put('roles/{role}/permissions', [RolePermissionController::class, 'syncRolePermissions']);
    Route::get('permissions', [RolePermissionController::class, 'permissions']);
    Route::get('settings', [SettingController::class, 'index']);
    Route::put('settings', [SettingController::class, 'update']);
    Route::put('settings/admin-pin', [AdminPinController::class, 'update']);
    Route::get('integrations', [SuperIntegrationController::class, 'integrationsIndex']);
    Route::get('integrations/outbox/summary', [SuperIntegrationController::class, 'outboxSummary']);
    Route::get('integrations/outbox', [SuperIntegrationController::class, 'outboxIndex']);
    Route::post('integrations/outbox/{integrationOutboxEntry}/requeue', [SuperIntegrationController::class, 'requeueOutboxEntry'])
        ->middleware('security.confirmed');
    Route::put('integrations/{provider}/{environment}', [SuperIntegrationController::class, 'integrationsUpsert']);
    Route::post('works/{work}/wipo-connect/outbox', [SuperIntegrationController::class, 'enqueueWipoConnectOutbox'])
        ->middleware('security.confirmed');
    Route::apiResource('languages', SuperLanguageController::class)->only(['index', 'store', 'update', 'destroy']);
});
